[package]
name = "ferrumc2_0"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async
tokio = { version = "1.38.0", features = ["full", "tracing"] }

# Error handling
anyhow = "1.0.86"
thiserror = "1.0.61"

# Logging
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
console-subscriber = "0.3.0"

# config / ser / de
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"
config = "0.14.0"
lazy_static = "1.4.0"
simdnbt = { version = "0.6.0", features = ["derive", "default"] }
fastnbt = "2.5.0"

# Binary
byteorder = "1.5.0"
include-flate = "0.3.0"
uuid = { version = "1.9.1", features = ["v4", "v3", "v5"] }

# OS
which = "6.0.1"

# Custom crates
ferrumc_macros = { path = "src/crates/ferrumc_macros" }

dashmap = "6.0.1"
rand = "0.9.0-alpha.1"
base64 = "0.22.1"
serde_json = "1.0.119"
async-trait = "0.1.77"
log = "0.4.22"
surrealdb = { version = "1.5.4", features = ["protocol-http"] }
fastanvil = "0.31.0"
serde_derive = "1.0.204"
