[package]
name = "ferrumc2_0"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async
tokio = { version = "1.38.0", features = ["full"] }

# Error handling
anyhow = "1.0.86"
thiserror = "1.0.61"

# Logging
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

# config / ser / de
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"
config = "0.14.0"
lazy_static = "1.4.0"

# Binary
byteorder = "1.5.0"
include-flate = "0.3.0"

# CLI
spinners = "4.1.1"
clap = { version = "4.5.8", features = ["derive"] }

# Custom crates
ferrumc_net = { path = "src/crates/ferrumc_net" }
ferrumc_macros = { path = "src/crates/ferrumc_macros" }
ferrumc_utils = { path = "src/crates/ferrumc_utils" }
