# The network address to bind to. Usually just 0.0.0.0 or 127.0.0.1 if you don't want to expose the server to the internet.s
host = "0.0.0.0"
# The port to bind to. Default is 25565.
port = 25565
# The message displayed in the server list.
motd = "A Minecraft Server written in Rust"
# The maximum number of players that can be connected at once.
max_players = 20
# How many network updates to process per second per user. 0 means no limit.
# This is the number of times per second the server will send updates to the client.
# Having this too low will cause noticable lag for clients but may improve server performance.
network_tick_rate = 0
# The world name to load. You can switch between mutliple worlds by changing this value.
world = "world"

[database]
# The path to the database folder. Generally you don't need to change this.
path = "data"
# The port the database runs on. This number was chosen at random and should be changed if it conflicts with another program.
port = 29325
# The mode the database should run in. Options are "file" and "memory". "file" is recommended for persistence.
# Memory mode will lose all data when the server is stopped and will have higher RAM use but will be noticeably faster.
mode = "file"